feat: adding globalAwait option
eta-dev/eta pull request #102
Opened 2021-04-02 11:09 UTC by SilentVoid13

Implements feature of #99. 

This feature allows us to add all data objects in an array and to await for it globally (only when the `globalAwait` option is set to true in the config).

This adds almost no overhead at runtime (adding a for loop to generate the array push, but that's neglectable overhead), because `Promise.all` just returns the value of synchronous functions and variables and only awaits for asynchronous functions. This could even be the default behavior when resolving templates (removing the option).

This allows us to speed things up a lot when having a lot of asynchronous functions in our data object.

Because this doesn't change anything about how this template engine works and just adds some extra speed, I don't think this is an out of scope feature, it is very useful when dealing with asynchronous functions.

2021-04-05 15:17 UTC, shadowtime2000 commented
Sorry for taking so long, I will take a look at this today.

2021-04-05 22:36 UTC, shadowtime2000 commented on src/compile-string.ts
> +    (config.globalAwait ? 'let prs = [];\n' : '') +
Do you think we could rename this to `_prs`? That is something I have seen many tools which need to add additional variables use so it doesn't conflict with the actual code.

2021-04-05 22:47 UTC, shadowtime2000 requested changes
Can you format this with prettier/eslint?

2021-04-05 23:28 UTC, SilentVoid13 commented
@shadowtime2000 This should be good !

2021-04-07 23:57 UTC, shadowtime2000 requested changes
I am still trying to figure out how exactly this would be tested, but if you know a way could you test this?

2021-04-13 21:14 UTC, SilentVoid13 commented
Hey @shadowtime2000, sorry for the late response.
I can't really think of a good way to test as I'm not familiar with unit tests in JS / TS.
We're really just adding everything in an array and awaiting for it so I don't think we need any new fancy tests compared to the existing ones.

2021-04-17 07:40 UTC, shadowtime2000 commented
@SilentVoid13 Sorry for the late response. 

Sorry, I am a little scared of merging something like this which is kind of hard to test so I am going to put this on hold I guess. Sorry again.

2023-06-13 20:25 UTC, nebrelbug commented
I'm going to close this as stale and because it's for Eta v2. I'd be open to accepting a pull request with this functionality for v3.

2023-06-13 20:25 UTC, closed without merging